name: dating-app-api
services:
  - name: api
    git:
      branch: main
      repo_clone_url: ${YOUR_GITHUB_REPO_URL}
    build_command: |
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install
      bun build ./src/index.ts --target=node --outdir=dist
    run_command: bun dist/index.js
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: JWT_ACCESS_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
    instance_size_slug: basic-xxs
    instance_count: 1
    source_dir: / 